
server:
  port: 0   # порт будет присвоен автоматически при публикации клиента

#  id приложения
spring:
  application:
    name: EurekaClient

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL куда будет происходить регистрация микросервисов
  instance:
    instance-id: ${spring.application.name}:${random.uuid}   # каждый экземпляр будет иметь уникальный ID

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'    # Формат вывода логов (сокращённый отн. формата по умолчанию)




